// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT46UmsrbdS6MKkMBxz0dIRVHHxDIzzxA',
    appId: '1:745315899081:web:0124ef42012e0d7c8cdf18',
    messagingSenderId: '745315899081',
    projectId: 'pulsecare-2026',
    authDomain: 'pulsecare-2026.firebaseapp.com',
    storageBucket: 'pulsecare-2026.firebasestorage.app',
    measurementId: 'G-0CTHJRDPKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhi377k9G2Xt2EDCWIuKmK9bPLiWksYJ8',
    appId: '1:745315899081:android:62ff30904b8a0b428cdf18',
    messagingSenderId: '745315899081',
    projectId: 'pulsecare-2026',
    storageBucket: 'pulsecare-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm9wkRVMQxNN6XA8k0N9fgKeC4Lq6R-94',
    appId: '1:745315899081:ios:c78cb848b2d2953e8cdf18',
    messagingSenderId: '745315899081',
    projectId: 'pulsecare-2026',
    storageBucket: 'pulsecare-2026.firebasestorage.app',
    iosBundleId: 'com.example.pulsecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm9wkRVMQxNN6XA8k0N9fgKeC4Lq6R-94',
    appId: '1:745315899081:ios:c78cb848b2d2953e8cdf18',
    messagingSenderId: '745315899081',
    projectId: 'pulsecare-2026',
    storageBucket: 'pulsecare-2026.firebasestorage.app',
    iosBundleId: 'com.example.pulsecare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT46UmsrbdS6MKkMBxz0dIRVHHxDIzzxA',
    appId: '1:745315899081:web:6e554e3c5fbc80048cdf18',
    messagingSenderId: '745315899081',
    projectId: 'pulsecare-2026',
    authDomain: 'pulsecare-2026.firebaseapp.com',
    storageBucket: 'pulsecare-2026.firebasestorage.app',
    measurementId: 'G-8MZ7EEQQLR',
  );
}
